### ISSUE TITLE
Support "Swan" based IPSec config

### ISSUE THREAD

**Issue by soloradish** [dennisstritzke/ipsec_exporter#15]
If user use "Swan"(libSwan/StrongSwan) based IPSec toolkits, There will be no configure info in ipsec.conf file. 

Have any chance to add a config file for this exporter, let user can spec the connection name?

**Comment by dennisstritzke** [comment]
How would you expect this to work? How would you like to configure the exporter? How are you specifying the tunnels within the Swan based toolkits?

**Comment by soloradish** [comment]
Swans' configure file has two schemas, Either one is no easy to write a parser. Could we just config the tunnels name we interested in **exporter's** config file or command line params? 

I use the StrongSwan's newer config schema. AFAIK, there are three Swan implementations [StrongSwan, OpenSwan, LibSwan]. both three have little difference in config schema. Is Really hard to support all these.

The config file I used

```
connections {

    gw-gw {
        local_addrs  = 192.168.0.1
        remote_addrs = 192.168.0.2
        proposals = aes256-sha1-modp1024
        local {
            auth = psk
            id = 192.168.0.1
        }
        remote {
            auth = psk
            id = 192.168.0.2
        }
        children {
            net-net {
                esp_proposals = aes256-sha1
                local_ts = 0.0.0.0/0
                remote_ts = 0.0.0.0/0
                life_time = 8h
                mark_in = 85
                mark_out = 85
            }
        }
        version = 2
        mobike = no
        reauth_time = 10800
    }
secrets {
    ike-1 {
        id-1a = 192.168.0.1
        id-1b = 192.168.0.2
        secret = "psk key here"
    }
include conf.d/*.conf
```

**Comment by dennisstritzke** [comment]
I think that it would be interesting to also support Swan based config files. Right now this isn't a priority for me.
Until this feature is available you could create an `/etc/ipsec.conf` file, which just lists the tunnel names. This approach would enable you to *configure* the IPsec exporter right now.

**Comment by ShujieDev** [comment]
@soloradish I rewrite some parts to make it work with the new strong swan version in this fork of the exporter
You can find it here:
[](https://github.com/Netnod/ipsec_exporter)
Now it also talk to vici protocal instead searching in the commandline output.
