### ISSUE TITLE
ignore commented lines

### ISSUE THREAD

**Issue by AFriemann** [dennisstritzke/ipsec_exporter#18]
The config loader logic isn't aware of commented lines and seems to pick them up anyway - I think this shouldn't happen.

I think they could easily be dropped here

https://github.com/dennisstritzke/ipsec_exporter/blob/237214f19fd9626c1b9c0f27edd6b5c3f188c8f9/ipsec/configuration.go#L111

Let me know if you agree and I'll gladly supply a PR

**Comment by dennisstritzke** [comment]
I definitely agree.

Thanks for bringing this up and I am happy to review your PR.

**Comment by AFriemann** [comment]
just pinging you again @dennisstritzke in case you didn't see the PR. Let me know if you have any requests! :)
