### ISSUE TITLE
Follow common pattern for naming exporters

### ISSUE THREAD

**Issue by supaflyster** [dennisstritzke/ipsec_exporter#22]
Hi! Thanks for your work with the ipsec exporter

Have few cosmetic suggestions, that might ease life for deployments:

1) remove "v" from the release version
We use ansible to deploy exporters to our hosts, and all of the exporters we use follow common naming pattern except ipsec-exporter

In ansible role we use following variables to build URL and filename

`prometheus_exporter_release_name: "{{prometheus_exporter_name}}-{{ prometheus_exporter_version }}.{{prometheus_exporter_arch }}"`
 `url: "https://{{prometheus_website_name}}/{{prometheus_github_username}}/{{prometheus_exporter_name}}/releases/download/v{{ prometheus_exporter_version }}/{{ prometheus_exporter_release_name }}.tar.gz"`

You can note "v" is used only in URL after releases/download/ but not in file name. And, as said before, this breaks this pattern for ipsec_exporter. You've introduced this in version 0.3. 

2) Pack binary into directory with release name.
Currently .tar.gz archive from Release page, after unpacking contains binary with full release name. As other exporters follow pattern of naming directory with full release name and putting binary with just exporter name inside:
e.g.
node_exporter has following structure:
`node_exporter-0.18.1.linux-amd64/node_exporter`
`node_exporter-0.17.0.linux-amd64/node_exporter`

So for ipsec_exporter we have to hack our standard deployment process to bypass those small things with naming, that is working for other exporters.

Hope these are not a big changes and are not breaking things for you and other users.

**Comment by dennisstritzke** [comment]
Thanks for explaining. I agree with your remarks. The next release will
1. Ditch the `v` from the filename again. But will retain the `v` in the Git Tag name, which also aligns with official exporters.
1. Include a subdirectory bearing the release name and the binary just named `ipsec_exporter`.

**Comment by dennisstritzke** [comment]
The naming alignment is available (and automated) starting from the current release v0.3.2.
