### ISSUE TITLE
Network binding

### ISSUE THREAD

**Issue by gunhu** [dennisstritzke/ipsec_exporter#26]
Hello,

It would be great if we can had more flexibility when we want to bind ipsec exporter to a specific network address (IPv4 or IPv6 with a network port) and keep intact the previous generic behavior (only port).

I already committed a pull request:

https://github.com/dennisstritzke/ipsec_exporter/pull/25

**Comment by saulp** [comment]
Quick question @dennisstritzke - any plans to implement the interface binding in the short term?

**Comment by dennisstritzke** [comment]
I incorporated (and amended) your changes in [this commit](https://github.com/dennisstritzke/ipsec_exporter/commit/61285ef5a0f8672921465c6d5606daa8fe7761f6). I rebased the changes to not include two fix commits within the history.

**Comment by dennisstritzke** [comment]
@saulp yep. Thanks for the ping. Will be within the next release.

**Comment by dennisstritzke** [comment]
You are able to set the network binding via the `--web.listen-address` parameter within [version 0.3.2](https://github.com/dennisstritzke/ipsec_exporter/releases/tag/v0.3.2) of the exporter.

**Comment by saulp** [comment]
Thanks! Quite possibly the quickest reply I've ever received on github..
Much appreciated.
