### ISSUE TITLE
do not require to restart the exporter when a tunnel is added/removed

### ISSUE THREAD

**Issue by perkons** [dennisstritzke/ipsec_exporter#28]
Hello,

currently having this setup:
Ubuntu 18.04.3 LTS (Bionic Beaver)
Kernel 4.15.0-62-generic
strongswan 5.6.2-1ubuntu2.4
/etc/ipsec.conf has "include /etc/ipsec.d/tunnels/*.conf" configured and tunnel config file are stored like /etc/ipsec.d/tunnels/{tunnel_name}.conf.

The problem is when removing/adding a tunnel conf file to /etc/ipsec.d/tunnels/ it does not show up/disappear automatically from metrics. You need to restart the ipsec_exporter for the tunnel to show up/disapear.

**Comment by dennisstritzke** [comment]
Hi perkons, the behaviour you describe is intended. Therefore, I am closing this issue.

**Comment by perkons** [comment]
Hi dennisstritzke, could you please tell me why this is intended? For me it is a problem as our NOC is adding and removing tunnels and not restarting the exporter.

**Comment by dennisstritzke** [comment]
As this exporter should run in production, it was my primary goal to make it as simple as anyhow possible. Therefore, I decided to only load the configuration on application start, which leaves way less corner cases to deal with.
