### ISSUE TITLE
I suspect ipsec value of REKEYED results in non-zero status from ipsec_exporter

### ISSUE THREAD

**Issue by mike-sixd** [dennisstritzke/ipsec_exporter#33]
Thanks for a really useful tool! We've been using it for about a year.

We're intermittently getting alerts about tunnels being down when they're up and working.

I suspect ipsec value of REKEYED results in non-zero status from ipsec_exporter

```
$ ipsec status | grep expires
       aaa{56474}:  REKEYED, TUNNEL, reqid 2, expires in 110 seconds
  aaa-ilo{56476}:  REKEYED, TUNNEL, reqid 6, expires in 3 minutes
```
https://github.com/dennisstritzke/ipsec_exporter/blob/9f6164f458358420a6cd41766eadd6f9df4aa17b/ipsec/status.go#L82-L83

**Comment by dennisstritzke** [comment]
Thank you for this improvement! Could you please remove the `ipsec_exporter` binary from your commit?
