### ISSUE TITLE
Cannot retrieve Tunnel status from within docker container

### ISSUE THREAD

**Issue by DerFels** [dennisstritzke/ipsec_exporter#36]
Hi,
I am trying to deploy the ipsec-exporter as a docker container on a host that is running ipsec tunnels. I have mounted the following files and folders, to be able to execute ipsec commands from within the container:
```
volumes:
      - /etc/ipsec.conf:/etc/ipsec.conf:ro
      - /usr/sbin/ipsec:/usr/sbin/ipsec
      - /usr/lib/ipsec/:/usr/lib/ipsec/
      - /lib/x86_64-linux-gnu/libcap.so.2:/lib/x86_64-linux-gnu/libcap.so.2
      - /var/run/:/var/run/
```

Within the container, I can successfully execute `ipsec status` and receive this status
```
no files found matching '/etc/strongswan.conf'
Security Associations (2 up, 0 connecting):
     Tunnel1[33]: ESTABLISHED 2 hours ago, X.X.X.X[x.x.x.x]...Y.Y.Y.Y[y.y.y.y]
     Tunnel1{187}:  INSTALLED, TUNNEL, reqid 20, ESP in UDP SPIs: c89e5ea2_i c8e8577e_o
     Tunnel1{187}:   X.X.X.X/24 === Y.Y.Y.Y/16
   ...
```

However, when I access the `/metrics` endpoint of the container, I see 
`ipsec-exporter_1  | time="2022-06-27T14:03:34Z" level=warning msg="Unable to retrieve the status of tunnel 'Tunnel1'. Reason: exit status 1" source="status.go:66"` in the logs.

I already disabled app-armor for `usr.lib.ipsec.charon` and `usr.lib.ipsec.stroke` but that didn't help. I am out of ideas and would appreciate any help :)

**Comment by bvidovic1** [comment]
Hi,

You are missing `/etc/ipsec.secrets` mounted.

This is what I have under volumes and it works:
```
    volumes:
      - /etc/ipsec.d:/etc/ipsec.d
      - /etc/ipsec.conf:/etc/ipsec.conf
      - /etc/ipsec.secrets:/etc/ipsec.secrets
```

**Comment by DerFels** [comment]
Awesome, thank you!
