### ISSUE TITLE
Tunnel configured as "auto=ignore" are reported as "down"

### ISSUE THREAD

**Issue by D3N14L** [dennisstritzke/ipsec_exporter#4]
Hi Dennis,

we have a VPN gateway that has at least one tunnel with the configuration parameter "auto=ignore". Which causes the ipsec damon to do exactly this - ignore this tunnel configuration. The ipsec-exporter obviously does not distinguish between tunnels that are down because of an error and tunnels that are in the config, but have been configured as down administratively (by setting auto=ignore). As the ipsec daemon actually does not load those tunnel configurations, it should be okay to do the same on the ipsec-exporter.

**Comment by dennisstritzke** [comment]
I totally agree. Interested in submitting a pull request?

**Comment by D3N14L** [comment]
I would love to, but I fear that I would first have to learn a bit of GoLang. Which is an item on my ToDo list for some time now...

**Comment by dennisstritzke** [comment]
I just release [v0.2](https://github.com/dennisstritzke/ipsec_exporter/releases/tag/v0.2) where `auto=ignore` connections are reported as ignored. Do these changes match your expectation? Feedback is appreciated!
