### ISSUE TITLE
Default port is already allocated

### ISSUE THREAD

**Issue by Tom-Fawcett** [dennisstritzke/ipsec_exporter#5]
Port 9101 is already used by HAProxy exporter

https://github.com/prometheus/prometheus/wiki/Default-port-allocations

https://prometheus.io/docs/instrumenting/writing_exporters/#port-numbers

It would be a small improvement to claim a free port and change the default to it :)

**Comment by dennisstritzke** [comment]
Thank you for your issue report. I claimed port `9536`.

The change will be included in the next release. Until then you are able to use the `--web.listen-address` flag to use another port.

**Comment by Tom-Fawcett** [comment]
Great :)

**Comment by dennisstritzke** [comment]
I released [version 0.3](https://github.com/dennisstritzke/ipsec_exporter/releases/tag/v0.3) of the exporter, which includes the change of this issue. Please be aware of the breaking changes.

Also there are additional metrics to track tunnel throughput.
